package com.company.IntelligentPlatform.common.model;

public interface IDefDocumentResource {
	
	int DOCUMENT_TYPE_RECEIPT = 1;

	int DOCUMENT_TYPE_VOUCHER = 2;

	int DOCUMENT_TYPE_BOOKINGNOTE = 3;
	
	int DOCUMENT_TYPE_FINANCE = 4;

	int DOCUMENT_TYPE_VEHICLERUNORDER = 5;

	int DOCUMENT_TYPE_VEHICLERUNORDERCONTRACT = 6;
	
	int DOCUMENT_TYPE_TRANSITORDER = 7;
	
	int DOCUMENT_TYPE_RECEIVERNOTE = 9;
	
	int DOCUMENT_TYPE_EXTERNALEXPRESSORDER = 10;
	
	int DOCUMENT_TYPE_INBOUNDDELIVERY = 11;
	
	int DOCUMENT_TYPE_OUTBOUNDDELIVERY = 12;
	
	int DOCUMENT_TYPE_INVENTORY_CHECKORDER = 13;
	
	int DOCUMENT_TYPE_INVENTORY_TRANSFER = 14;
	
	int DOCUMENT_TYPE_SALESORDER = 15;
	
	int DOCUMENT_TYPE_PURCHASE = 16;
	
	int DOCUMENT_TYPE_PRODUCTIONORDER = 17;
	
	int DOCUMENT_TYPE_SALESRETURNORDER = 18;
	
	int DOCUMENT_TYPE_SALESCONTRACT = 19;
	
	int DOCUMENT_TYPE_PURCHASECONTRACT = 20;
	
	int DOCUMENT_TYPE_BIDDINGINVITATIONORDER = 23;
	
	int DOCUMENT_TYPE_INQUIRY = 24;
	
	int DOCUMENT_TYPE_PRODUCTIONPLAN = 25;
	
	int DOCUMENT_TYPE_PRODPICKINGORDER = 26;
	
	int DOCUMENT_TYPE_PRODRETURNORDER = 27;
	
	int DOCUMENT_TYPE_QUALITYINSPECTORDER = 28;
	
	int DOCUMENT_TYPE_PRODORDERREPORT = 29;
	
	int DOCUMENT_TYPE_WAREHOUSESTOREITEM = 30;
	
	int DOCUMENT_TYPE_PRODUCTORDERITEM = 31;
	
	int DOCUMENT_TYPE_PRODUCTPLANITEM = 32;

	int DOCUMENT_TYPE_SALESFORCAST = 33;

	int DOCUMENT_TYPE_PURCHASEREQUEST = 34;

	int DOCUMENT_TYPE_PURCHASERETURNORDER = 35;

	int DOCUMENT_TYPE_BILLOFMATERIALTEMPLATE = 36;

	int DOCUMENT_TYPE_BILLOFMATERIALORDER = 37;

	int DOCUMENT_TYPE_WASTEPROCESSORDER = 38;

	int DOCUMENT_TYPE_REPAIRPRODORDER = 39;

	int DOCUMENT_TYPE_REPAIRPRODORDERITEM = 40;

}
