package com.company.IntelligentPlatform.common.service;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.company.IntelligentPlatform.common.service.ServiceDropdownListHelper;
import com.company.IntelligentPlatform.common.service.ServiceEntityInstallationException;
import com.company.IntelligentPlatform.common.service.ServiceLanHelper;
import com.company.IntelligentPlatform.common.model.ServiceEntityDateHelper;
import com.company.IntelligentPlatform.common.model.ServiceEntityStringHelper;

@Service
public class ServiceChartHelper {

    public static final String CHARTTYPE_PIE = "pie";

    public static final String CHARTTYPE_COLUMN = "column";

    public static final String CHARTTYPE_SPLINE = "spline";

    public static final String RES_FILENAME_CHARTTYPE = "ChartType";

    @Autowired
    protected ServiceDropdownListHelper serviceDropdownListHelper;

    public Map<String, String> getChartTypeMap()
            throws ServiceEntityInstallationException, IOException {
        Locale locale = ServiceLanHelper.getDefault();
        String path = ServiceChartHelper.class.getResource("").getPath();
        Map<String, String> unitMap = serviceDropdownListHelper.getDropDownMap(path, RES_FILENAME_CHARTTYPE, locale);
        return unitMap;
    }

    /**
     * Generate the time slot list
     *
     * @param unit
     * @param startDate
     * @param endDate
     * @return
     */
    public static List<ServiceChartTimeSlot> genChartTimeSlots(int unit,
                                                               Date startDate, Date endDate) {
        if (unit == ServiceCalendarHelper.UNIT_MONTH) {
            return genMonthTimeSlot(startDate, endDate);
        }
        if (unit == ServiceCalendarHelper.UNIT_WEEK) {
            return genWeeklyTimeSlot(startDate, endDate);
        }
        if (unit == ServiceCalendarHelper.UNIT_DAY) {
            return genDailyTimeSlot(startDate, endDate);
        }
        return null;
    }

    protected static List<ServiceChartTimeSlot> genMonthTimeSlot(
            Date startDate, Date endDate) {
        // [Step1] calculate the size of time slot list
        List<ServiceChartTimeSlot> timeSlots = new ArrayList<ServiceChartTimeSlot>();
        Calendar startCalendar = Calendar.getInstance();
        startCalendar.setTime(startDate);
        Calendar endCalendar = Calendar.getInstance();
        endCalendar.setTime(endDate);
        int size = ServiceEntityDateHelper.getDiffMonth(startCalendar,
                endCalendar);
        Calendar tmpCalendar = startCalendar;
        // [Step2] process of generate time slot list
        for (int i = 0; i < size; i++) {
            ServiceChartTimeSlot newSlot = new ServiceChartTimeSlot();
            newSlot.setStartDate(tmpCalendar.getTime());
            int actualMonth = tmpCalendar.get(Calendar.MONTH) + 1;
            String xTSLabel = tmpCalendar.get(Calendar.YEAR) + "-"
                    + actualMonth;
            xTSLabel = xTSLabel + "(" + actualMonth + "." + tmpCalendar.get(Calendar.DAY_OF_MONTH);
            tmpCalendar.add(Calendar.MONTH, 1);
            newSlot.setEndDate(tmpCalendar.getTime());
            int actualEndMonth = tmpCalendar.get(Calendar.MONTH) + 1;
            xTSLabel = xTSLabel + "-" + actualEndMonth + "." + tmpCalendar.get(Calendar.DAY_OF_MONTH) + ")";
            newSlot.setxTimeSlotLabel(xTSLabel);
            timeSlots.add(newSlot);
        }
        // [Step3] post step: check if the last data generated by time slot
        // cover the real last date, if not, post add extra time slot
        long diff = tmpCalendar.getTime().getTime() - endDate.getTime();
        if (diff < 0) {
            ServiceChartTimeSlot newSlot = new ServiceChartTimeSlot();
            newSlot.setStartDate(tmpCalendar.getTime());
            int actualMonth = tmpCalendar.get(Calendar.MONTH) + 1;
            String xTSLabel = tmpCalendar.get(Calendar.YEAR) + "-"
                    + actualMonth;
            xTSLabel = xTSLabel + "(" + actualMonth + "." + tmpCalendar.get(Calendar.DAY_OF_MONTH);
            tmpCalendar.add(Calendar.MONTH, 1);
            newSlot.setEndDate(tmpCalendar.getTime());
            int actualEndMonth = tmpCalendar.get(Calendar.MONTH) + 1;
            xTSLabel = xTSLabel + "-" + actualEndMonth + "." + tmpCalendar.get(Calendar.DAY_OF_MONTH) + ")";
            newSlot.setxTimeSlotLabel(xTSLabel);
            timeSlots.add(newSlot);
        }
        return timeSlots;
    }

    protected static List<ServiceChartTimeSlot> genWeeklyTimeSlot(
            Date startDate, Date endDate) {
        // [Step1] calculate the size of time slot list
        List<ServiceChartTimeSlot> timeSlots = new ArrayList<ServiceChartTimeSlot>();
        Calendar startCalendar = Calendar.getInstance();
        startCalendar.setTime(startDate);
        // Calendar endCalendar = Calendar.getInstance();
        int size = (int) (ServiceEntityDateHelper.getDiffWeeks(startDate,
                endDate) + 1);
        Calendar tmpCalendar = startCalendar;
        // [Step2] process of generate time slot list
        for (int i = 0; i < size; i++) {
            ServiceChartTimeSlot newSlot = new ServiceChartTimeSlot();
            newSlot.setStartDate(tmpCalendar.getTime());
            tmpCalendar.add(Calendar.WEEK_OF_YEAR, 1);
            int actualWeek = tmpCalendar.get(Calendar.WEEK_OF_YEAR) + 1;
            String xTSLabel = tmpCalendar.get(Calendar.YEAR) + "-"
                    + actualWeek;
            newSlot.setxTimeSlotLabel(xTSLabel);
            newSlot.setEndDate(tmpCalendar.getTime());
            timeSlots.add(newSlot);
        }
        // [Step3] post step: check if the last data generated by time slot
        // cover the real last date, if not, post add extra time slot
        long diff = tmpCalendar.getTime().getTime() - endDate.getTime();
        if (diff < 0) {
            ServiceChartTimeSlot newSlot = new ServiceChartTimeSlot();
            newSlot.setStartDate(tmpCalendar.getTime());
            tmpCalendar.add(Calendar.WEEK_OF_YEAR, 1);
            int actualWeek = tmpCalendar.get(Calendar.WEEK_OF_YEAR) + 1;
            String xTSLabel = tmpCalendar.get(Calendar.YEAR) + "-"
                    + actualWeek;
            newSlot.setxTimeSlotLabel(xTSLabel);
            newSlot.setEndDate(tmpCalendar.getTime());
            timeSlots.add(newSlot);
        }
        return timeSlots;
    }

    protected static List<ServiceChartTimeSlot> genDailyTimeSlot(
            Date startDate, Date endDate) {
        // [Step1] calculate the size of time slot list
        List<ServiceChartTimeSlot> timeSlots = new ArrayList<ServiceChartTimeSlot>();
        Calendar startCalendar = Calendar.getInstance();
        startCalendar.setTime(startDate);
        // Calendar endCalendar = Calendar.getInstance();
        int size = (int) (ServiceEntityDateHelper.getDiffDays(startDate,
                endDate) + 1);
        Calendar tmpCalendar = startCalendar;
        // [Step2] process of generate time slot list
        for (int i = 0; i < size; i++) {
            ServiceChartTimeSlot newSlot = new ServiceChartTimeSlot();
            newSlot.setStartDate(tmpCalendar.getTime());
            tmpCalendar.add(Calendar.DATE, 1);
            int actualDay = tmpCalendar.get(Calendar.DAY_OF_MONTH) + 1;
            int actualMonth = tmpCalendar.get(Calendar.MONTH) + 1;
            String xTSLabel = tmpCalendar.get(Calendar.YEAR) + "-" + actualMonth + "."
                    + actualDay;
            newSlot.setxTimeSlotLabel(xTSLabel);
            newSlot.setEndDate(tmpCalendar.getTime());
            timeSlots.add(newSlot);
        }
        // [Step3] post step: check if the last data generated by time slot
        // cover the real last date, if not, post add extra time slot
        long diff = tmpCalendar.getTime().getTime() - endDate.getTime();
        if (diff < 0) {
            ServiceChartTimeSlot newSlot = new ServiceChartTimeSlot();
            newSlot.setStartDate(tmpCalendar.getTime());
            tmpCalendar.add(Calendar.DATE, 1);
            int actualDay = tmpCalendar.get(Calendar.DAY_OF_MONTH) + 1;
            int actualMonth = tmpCalendar.get(Calendar.MONTH) + 1;
            String xTSLabel = tmpCalendar.get(Calendar.YEAR) + "-" + actualMonth + "."
                    + actualDay;
            newSlot.setxTimeSlotLabel(xTSLabel);
            newSlot.setEndDate(tmpCalendar.getTime());
            timeSlots.add(newSlot);
        }
        return timeSlots;
    }

    public static ServiceComChartUIModel convertChartModelToUI(ServiceComChartModel charModel) {
        ServiceComChartUIModel chartUIModel = new ServiceComChartUIModel();
        List<ServiceChartDataSeries> dataSeries = charModel.getDataSeries();
        List<ServiceChartDataSeriesUIModel> dataUISeries = new ArrayList<ServiceChartDataSeriesUIModel>();
        for (ServiceChartDataSeries series : dataSeries) {
            ServiceChartDataSeriesUIModel seriesUIModel = new ServiceChartDataSeriesUIModel();
            seriesUIModel.setData(series.getValueList());
            seriesUIModel.setName(series.getObjectName());
            if (series.getChartType() != null && !series.getChartType().equals(ServiceEntityStringHelper.EMPTYSTRING)) {
                seriesUIModel.setType(series.getChartType());
            }
            dataUISeries.add(seriesUIModel);
        }
        chartUIModel.setSeries(dataUISeries);
        chartUIModel.setCategories(charModel.getCategories());
        chartUIModel.setSubTitle(charModel.getSubTitle());
        chartUIModel.setTitle(charModel.getTitle());
        chartUIModel.setyAxisTitle(charModel.getyAxisTitle());
        // Convert pie chart series UI model
        ServicePieChartDataSeriesUIModel pieChartDataSeriesUIModel = convertToPieSeries(chartUIModel);
        List<ServicePieChartDataSeriesUIModel> pieSeries = new ArrayList<ServicePieChartDataSeriesUIModel>();
        pieSeries.add(pieChartDataSeriesUIModel);
        chartUIModel.setPieSeries(pieSeries);
        return chartUIModel;
    }

    public static ServicePieChartDataSeriesUIModel convertToPieSeries(ServiceComChartUIModel chartUIModel) {
        ServicePieChartDataSeriesUIModel pieChartDataSeriesUIModel = new ServicePieChartDataSeriesUIModel();
        pieChartDataSeriesUIModel.setName(chartUIModel.getTitle());
        List<ServicePieChartDataUnion> dataUnionList = new ArrayList<ServicePieChartDataUnion>();
        List<ServiceChartDataSeriesUIModel> dataSeries = chartUIModel.getSeries();
        double grossAmount = 0;
        for (ServiceChartDataSeriesUIModel series : dataSeries) {
            ServicePieChartDataUnion dataUnion = new ServicePieChartDataUnion();
            dataUnion.setName(series.getName());
            double averageAmount = 0;
            if (series.getData() == null || series.getData().size() == 0) {
                averageAmount = 0;
            } else {
                for (double value : series.getData()) {
                    averageAmount = value + averageAmount;
                }
                averageAmount = averageAmount / (series.getData().size());
            }
            dataUnion.setY(averageAmount);
            grossAmount = grossAmount + dataUnion.getY();
            dataUnionList.add(dataUnion);
        }
        // post-process y value
        for (ServicePieChartDataUnion dataUnion : dataUnionList) {
            if (grossAmount != 0) {
                dataUnion.setY(dataUnion.getY() / grossAmount * 100);
            }
        }
        pieChartDataSeriesUIModel.setData(dataUnionList);
        return pieChartDataSeriesUIModel;
    }

    /**
     * [Internal method] Merge value to data series list by checking existence
     * of object UUID
     *
     * @param dataSeries
     * @param objectUUID
     * @param value
     */
    public void mergeDataSeries(List<ServiceChartDataSeries> dataSeries,
                                String objectUUID, Double value) {
        for (ServiceChartDataSeries serviceChartDataSeries : dataSeries) {
            if (objectUUID.equals(serviceChartDataSeries.getObjectUUID())) {
                serviceChartDataSeries.getValueList().add(value);
            }
        }
    }

}
