package com.company.IntelligentPlatform.common.service;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Service;
import com.company.IntelligentPlatform.common.controller.ServiceUIModelExtension;
import com.company.IntelligentPlatform.common.controller.ServiceUIModelExtensionUnion;
import com.company.IntelligentPlatform.common.controller.UIModelNodeConfigPreCondition;
import com.company.IntelligentPlatform.common.controller.UIModelNodeMapConfigure;
import com.company.IntelligentPlatform.common.service.SearchConfigConnectCondition;
import com.company.IntelligentPlatform.common.model.IReferenceNodeFieldConstant;
import com.company.IntelligentPlatform.common.model.IServiceEntityNodeFieldConstant;
import com.company.IntelligentPlatform.common.model.ServiceEntityConfigureException;
import com.company.IntelligentPlatform.common.model.ServiceBasicKeyStructure;
import com.company.IntelligentPlatform.common.model.ServiceEntityNode;
import com.company.IntelligentPlatform.common.model.ServiceCollectionsHelper;
import com.company.IntelligentPlatform.common.model.ServiceEntityFieldsHelper;
import com.company.IntelligentPlatform.common.model.ServiceEntityStringHelper;

@Service
public class ServiceModelExtensionHelper {

	/**
	 * Main logic to generate ServiceBasicKeyStructure List, for retrieving data
	 * dynamically condition
	 * 
	 * @param uiModelNodeMapConfigure
	 * @return
	 * @throws SecurityException
	 * @throws NoSuchFieldException
	 * @throws IllegalAccessException
	 * @throws IllegalArgumentException
	 */
	public static List<ServiceBasicKeyStructure> generateKeyStructFromNodeMapConfigure(
			UIModelNodeMapConfigure uiModelNodeMapConfigure,
			ServiceEntityNode rawEntityNode, String client)
			throws NoSuchFieldException, SecurityException,
			IllegalArgumentException, IllegalAccessException {
		/*
		 * [Step1][Common header] add client header
		 */
		List<ServiceBasicKeyStructure> resultList = new ArrayList<>();
		
		/*
		 * [Step2] key structure generated by preconditions setting
		 */
		if (!ServiceCollectionsHelper.checkNullList(uiModelNodeMapConfigure
				.getPreConditions())) {
			List<UIModelNodeConfigPreCondition> preConditions = uiModelNodeMapConfigure
					.getPreConditions();
			for (UIModelNodeConfigPreCondition preCondition : preConditions) {
				resultList.add(new ServiceBasicKeyStructure(preCondition.getFieldValue(), preCondition.getFieldName()));
			}
		}
		/*
		 * [Step2.5] key structure generated by connection condition.
		 */
		if(!ServiceCollectionsHelper.checkNullList(uiModelNodeMapConfigure.getConnectionConditions())){
			for(SearchConfigConnectCondition searchConfigConnectCondition:uiModelNodeMapConfigure.getConnectionConditions()){
				Field refBaseField = ServiceEntityFieldsHelper.getServiceField(
						rawEntityNode.getClass(),
						searchConfigConnectCondition.getSourceFieldName());
				refBaseField.setAccessible(true);
				Object keyValue = refBaseField.get(rawEntityNode);
				if(keyValue == null || ServiceEntityStringHelper.checkNullString(keyValue.toString())){
					continue;
				}
				resultList.add(new ServiceBasicKeyStructure(refBaseField.get(rawEntityNode),
						searchConfigConnectCondition.getTargetFieldName().toString()));
			}
		}
		/**
		 * [Step3] Core key structure generated by relationship to parent
		 */
		// [Case] UIModelNodeMapConfigure.TOBASENODE_TO_PARENT
		if (uiModelNodeMapConfigure.getToBaseNodeType() == UIModelNodeMapConfigure.TOBASENODE_TO_PARENT) {
			String keyValue = rawEntityNode.getUuid();
			if(!ServiceEntityStringHelper.checkNullString(keyValue)){
				resultList.add(new ServiceBasicKeyStructure(rawEntityNode.getUuid(), IServiceEntityNodeFieldConstant.PARENTNODEUUID));
			}
			//return resultList;
		}
		// [Case] UIModelNodeMapConfigure.TOBASENODE_TO_ROOT
		if (uiModelNodeMapConfigure.getToBaseNodeType() == UIModelNodeMapConfigure.TOBASENODE_TO_ROOT) {
			ServiceBasicKeyStructure keyStructure = new ServiceBasicKeyStructure();
			String keyValue = rawEntityNode.getUuid();
			if(!ServiceEntityStringHelper.checkNullString(keyValue)){
				keyStructure.setKeyValue(rawEntityNode.getUuid());
				keyStructure
						.setKeyName(IServiceEntityNodeFieldConstant.ROOTNODEUUID);
				resultList.add(keyStructure);
			}
			//return resultList;
		}
		// [Case] UIModelNodeMapConfigure.TOBASENODE_TO_CHILD
		if (uiModelNodeMapConfigure.getToBaseNodeType() == UIModelNodeMapConfigure.TOBASENODE_TO_CHILD) {
			ServiceBasicKeyStructure keyStructure = new ServiceBasicKeyStructure();
			String keyValue = rawEntityNode.getParentNodeUUID();
			if(!ServiceEntityStringHelper.checkNullString(keyValue)){
				keyStructure.setKeyValue(rawEntityNode.getParentNodeUUID());
				keyStructure.setKeyName(IServiceEntityNodeFieldConstant.UUID);
				resultList.add(keyStructure);
			}
			//return resultList;
		}
		// [Case] UIModelNodeMapConfigure.TOBASENODE_REFTO_TARGET
		if (uiModelNodeMapConfigure.getToBaseNodeType() == UIModelNodeMapConfigure.TOBASENODE_REFTO_TARGET) {
			ServiceBasicKeyStructure keyStructure = new ServiceBasicKeyStructure();
			Field uuidField = ServiceEntityFieldsHelper.getServiceField(
					rawEntityNode.getClass(),
					IServiceEntityNodeFieldConstant.UUID);
			uuidField.setAccessible(true);
			Object keyValue = uuidField.get(rawEntityNode);
			if(keyValue != null && !ServiceEntityStringHelper.checkNullString(keyValue.toString())){
				keyStructure.setKeyValue(uuidField.get(rawEntityNode));
				keyStructure.setKeyName(IReferenceNodeFieldConstant.REFUUID);
				resultList.add(keyStructure);
			}
			//return resultList;
		}

		// [Case] UIModelNodeMapConfigure.TOBASENODE_REFTO_SOURCE
		if (uiModelNodeMapConfigure.getToBaseNodeType() == UIModelNodeMapConfigure.TOBASENODE_REFTO_SOURCE) {
			ServiceBasicKeyStructure keyStructure = new ServiceBasicKeyStructure();
			Field refUUIDField = ServiceEntityFieldsHelper.getServiceField(
					rawEntityNode.getClass(),
					IReferenceNodeFieldConstant.REFUUID);
			refUUIDField.setAccessible(true);
			Object keyValue = refUUIDField.get(rawEntityNode);
			if(keyValue != null && !ServiceEntityStringHelper.checkNullString(keyValue.toString())){
				keyStructure.setKeyValue(keyValue);
				keyStructure.setKeyName(IServiceEntityNodeFieldConstant.UUID);			
				resultList.add(keyStructure);	
			}
			//return resultList;
		}
		
		// [Case] UIModelNodeMapConfigure.TOBASENODE_TO_ROOT
		if (uiModelNodeMapConfigure.getToBaseNodeType() == UIModelNodeMapConfigure.TOBASENODE_ROOT_TO_CHILD) {
			ServiceBasicKeyStructure keyStructure = new ServiceBasicKeyStructure();
			String keyValue = rawEntityNode.getRootNodeUUID();
			if(!ServiceEntityStringHelper.checkNullString(keyValue)){
				keyStructure.setKeyValue(rawEntityNode.getRootNodeUUID());
				keyStructure.setKeyName(IServiceEntityNodeFieldConstant.UUID);
				resultList.add(keyStructure);
			}
			//return resultList;
		}
		if(resultList.size() == 0){
			return null;
		}
		ServiceBasicKeyStructure clientHeader = new ServiceBasicKeyStructure();
		clientHeader.setKeyName(IServiceEntityNodeFieldConstant.CLIENT);
		clientHeader.setKeyValue(client);
		resultList.add(clientHeader);
		return resultList;
	}

	/**
	 * Filter out the sub node map list
	 * 
	 * @param uiModelNodeMapList
	 * @param curNodeMapConfigure
	 * @return
	 */
	public static List<UIModelNodeMapConfigure> filterChildNodeMapList(
			List<UIModelNodeMapConfigure> uiModelNodeMapList,
			UIModelNodeMapConfigure curNodeMapConfigure) {
		if (ServiceCollectionsHelper.checkNullList(uiModelNodeMapList)) {
			return null;
		}
		List<UIModelNodeMapConfigure> resultList = new ArrayList<>();
		for (UIModelNodeMapConfigure uiModelNodeMapConfigure : uiModelNodeMapList) {
			if (ServiceEntityStringHelper
					.checkNullString(uiModelNodeMapConfigure
							.getBaseNodeInstID())) {
				continue;
			}
			if (uiModelNodeMapConfigure.getBaseNodeInstID().equals(
					curNodeMapConfigure.getNodeInstID())) {
				resultList.add(uiModelNodeMapConfigure);
			}
		}
		return resultList;
	}

	/**
	 * Filter out the target node instance by node inst id.
	 * @param uiModelNodeMapList
	 * @return
	 */
	public static UIModelNodeMapConfigure filterNodeMapConfigureByNodeInstId(List<UIModelNodeMapConfigure> uiModelNodeMapList, String nodeInstId) {
		if (ServiceCollectionsHelper.checkNullList(uiModelNodeMapList)) {
			return null;
		}
		for (UIModelNodeMapConfigure uiModelNodeMapConfigure : uiModelNodeMapList) {
			if (nodeInstId.equals(uiModelNodeMapConfigure.getNodeInstID())) {
				return uiModelNodeMapConfigure;
			}
		}
		return null;
	}
	
	/**
	 * Filter out the first node map configure with NO base node
	 * @param uiModelNodeMapList
	 * @return
	 */
	public static UIModelNodeMapConfigure getFirstNodeMapConfigure(List<UIModelNodeMapConfigure> uiModelNodeMapList) {
		if (ServiceCollectionsHelper.checkNullList(uiModelNodeMapList)) {
			return null;
		}
		for (UIModelNodeMapConfigure uiModelNodeMapConfigure : uiModelNodeMapList) {
			if (ServiceEntityStringHelper.checkNullString(uiModelNodeMapConfigure.getBaseNodeInstID())) {
				return uiModelNodeMapConfigure;
			}
		}
		return null;
	}
	
	private static ServiceUIModelExtensionUnion _getCurLayerExtensionUnionbyId(String nodeInstId, ServiceUIModelExtension curUIModelExtension)
			throws ServiceEntityConfigureException {
		List<ServiceUIModelExtensionUnion> unionList =  curUIModelExtension.genUIModelExtensionUnion();
		if(ServiceCollectionsHelper.checkNullList(unionList)){
			return null;
		}
		for(ServiceUIModelExtensionUnion serviceUIModelExtensionUnion:unionList){
			if(serviceUIModelExtensionUnion.getNodeInstId().equals(nodeInstId)){
				return serviceUIModelExtensionUnion;
			}
		}
		return null;
	}
	
	public static class ExtensionUnionResponse{
		
		ServiceUIModelExtensionUnion serviceUIModelExtensionUnion;
		
		ServiceUIModelExtension serviceUIModelExtension;

		public ExtensionUnionResponse(
				ServiceUIModelExtensionUnion serviceUIModelExtensionUnion,
				ServiceUIModelExtension serviceUIModelExtension) {
			super();
			this.serviceUIModelExtensionUnion = serviceUIModelExtensionUnion;
			this.serviceUIModelExtension = serviceUIModelExtension;
		}

		public ServiceUIModelExtensionUnion getServiceUIModelExtensionUnion() {
			return serviceUIModelExtensionUnion;
		}

		public void setServiceUIModelExtensionUnion(
				ServiceUIModelExtensionUnion serviceUIModelExtensionUnion) {
			this.serviceUIModelExtensionUnion = serviceUIModelExtensionUnion;
		}

		public ServiceUIModelExtension getServiceUIModelExtension() {
			return serviceUIModelExtension;
		}

		public void setServiceUIModelExtension(
				ServiceUIModelExtension serviceUIModelExtension) {
			this.serviceUIModelExtension = serviceUIModelExtension;
		}
		
	}
	
	/**
	 * Get the ServiceUIModelExtensionUnion instance recursive by searching into child node configure
	 * @param nodeInstId
	 * @param curUIModelExtension
	 * @return
	 */
	public static ExtensionUnionResponse getUIModelExtensionByNodeInstId(String nodeInstId, ServiceUIModelExtension curUIModelExtension)
			throws ServiceEntityConfigureException {
		List<ServiceUIModelExtensionUnion> unionList =  curUIModelExtension.genUIModelExtensionUnion();
		if(ServiceCollectionsHelper.checkNullList(unionList)){
			return null;
		}
		for(ServiceUIModelExtensionUnion serviceUIModelExtensionUnion:unionList){
			if(serviceUIModelExtensionUnion.getNodeInstId().equals(nodeInstId)){
				return new ExtensionUnionResponse(serviceUIModelExtensionUnion, curUIModelExtension);
			}
		}
		// Navigate to sub child list
		List<ServiceUIModelExtension> subUIModelList = curUIModelExtension.getChildUIModelExtensions();
		if(ServiceCollectionsHelper.checkNullList(subUIModelList)){
			return null;
		}
		for(ServiceUIModelExtension subServiceUIModelExtension:subUIModelList){
			ServiceUIModelExtensionUnion subExtensionUnion =  _getCurLayerExtensionUnionbyId(nodeInstId, subServiceUIModelExtension);
			if(subExtensionUnion != null){
				return new ExtensionUnionResponse(subExtensionUnion, subServiceUIModelExtension);
			}
		}
		for(ServiceUIModelExtension subServiceUIModelExtension:subUIModelList){
			ExtensionUnionResponse subExtensionUnionResponse = getUIModelExtensionByNodeInstId(nodeInstId, subServiceUIModelExtension);
			if(subExtensionUnionResponse!= null){
				return subExtensionUnionResponse;
			}
		}
		return null;
	}
	
}
