package com.company.IntelligentPlatform.common.config;

/**
 * Immutable security principal attached to the Spring Security context after
 * a valid JWT token is verified by {@link JwtAuthFilter}.
 *
 * <p>REST controllers can retrieve the current principal from
 * {@link org.springframework.security.core.context.SecurityContextHolder} to
 * obtain the caller's identity and tenant context without an extra DB lookup:</p>
 * <pre>
 *   JwtPrincipal principal = (JwtPrincipal)
 *       SecurityContextHolder.getContext().getAuthentication().getPrincipal();
 *   String userUUID = principal.getUuid();
 *   String client   = principal.getClient();
 * </pre>
 *
 * <p>The four fields map directly to the JWT claims generated by
 * {@link JwtUtil#generateToken}.</p>
 */
public class JwtPrincipal {

    /** The user's business ID (JWT {@code sub}), e.g. "U001". */
    private final String userId;

    /** The user's UUID primary key (JWT {@code uuid} claim). */
    private final String uuid;

    /** The tenant/client discriminator (JWT {@code client} claim). */
    private final String client;

    /** The user's preferred UI language (JWT {@code languageCode} claim). */
    private final String languageCode;

    /**
     * Constructs a principal from the four claims extracted from a verified JWT.
     *
     * @param userId       the user's business ID (JWT subject)
     * @param uuid         the user's UUID primary key
     * @param client       the tenant/client code
     * @param languageCode the user's preferred language code
     */
    public JwtPrincipal(String userId, String uuid, String client, String languageCode) {
        this.userId       = userId;
        this.uuid         = uuid;
        this.client       = client;
        this.languageCode = languageCode;
    }

    /**
     * Returns the user's business ID (the JWT {@code sub} claim).
     *
     * @return business ID string, e.g. "U001"
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Returns the user's UUID primary key.
     *
     * <p>Pass this value to service-layer methods that accept
     * {@code userUUID}.</p>
     *
     * @return UUID string
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Returns the tenant/client discriminator for this session.
     *
     * <p>Pass this value to all service-layer calls that accept
     * {@code client}.</p>
     *
     * @return client/tenant code string
     */
    public String getClient() {
        return client;
    }

    /**
     * Returns the user's preferred UI language code.
     *
     * @return language code (e.g. "en", "zh"), or empty string if not set
     */
    public String getLanguageCode() {
        return languageCode;
    }

    @Override
    public String toString() {
        return "JwtPrincipal{userId='" + userId + "', client='" + client + "'}";
    }
}
