-- Standard DocMatItemNode base column block (ServiceEntityNode + ReferenceNode + DocMatItemNode)
-- Used by all tables below. Each table adds its own entity-specific columns after the base.

-- InquiryMaterialItem existed in V2 but was created before reservedMatItemUUID/reservedDocType were added to DocMatItemNode
ALTER TABLE `logistics`.`InquiryMaterialItem`
  ADD COLUMN IF NOT EXISTS `reservedMatItemUUID` varchar(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `reservedDocType` int DEFAULT '0',
  ADD COLUMN IF NOT EXISTS `reservedDocMatItemArrayUUID` text;

-- schema: logistics
CREATE TABLE IF NOT EXISTS `logistics`.`PurchaseRequestMaterialItem` (
  `uuid` varchar(100) NOT NULL,
  `client` varchar(100) DEFAULT NULL,
  `id` varchar(100) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `parentNodeUUID` varchar(100) DEFAULT NULL,
  `rootNodeUUID` varchar(100) DEFAULT NULL,
  `nodeLevel` int DEFAULT '0',
  `serviceEntityName` varchar(100) DEFAULT NULL,
  `nodeName` varchar(100) DEFAULT NULL,
  `createdBy` varchar(100) DEFAULT NULL,
  `createdTime` datetime DEFAULT NULL,
  `lastUpdateBy` varchar(100) DEFAULT NULL,
  `lastUpdateTime` datetime DEFAULT NULL,
  `nodeSpecifyType` int DEFAULT '0',
  `note` varchar(2000) DEFAULT NULL,
  `resEmployeeUUID` varchar(100) DEFAULT NULL,
  `resOrgUUID` varchar(100) DEFAULT NULL,
  `refUUID` varchar(100) DEFAULT NULL,
  `refSEName` varchar(100) DEFAULT NULL,
  `refNodeName` varchar(100) DEFAULT NULL,
  `refPackageName` varchar(100) DEFAULT NULL,
  `itemStatus` int DEFAULT '0',
  `refUnitUUID` varchar(100) DEFAULT NULL,
  `refMaterialSKUUUID` varchar(100) DEFAULT NULL,
  `amount` double DEFAULT '0',
  `itemPrice` double DEFAULT '0',
  `unitPrice` double DEFAULT '0',
  `currencyCode` varchar(100) DEFAULT NULL,
  `prevDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevDocType` int DEFAULT '0',
  `nextDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextDocType` int DEFAULT '0',
  `refFinMatItemUUID` varchar(100) DEFAULT NULL,
  `productionBatchNumber` varchar(100) DEFAULT NULL,
  `purchaseBatchNumber` varchar(100) DEFAULT NULL,
  `homeDocumentType` int DEFAULT '34',
  `materialStatus` int DEFAULT '1',
  `nextDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `prevDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `itemPriceDisplay` double DEFAULT '0',
  `unitPriceDisplay` double DEFAULT '0',
  `prevProfDocType` int DEFAULT '0',
  `prevProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevProfDocMatItemArrayUUID` text,
  `nextProfDocType` int DEFAULT '0',
  `nextProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextProfDocMatItemArrayUUID` text,
  `reserveTargetDocType` int DEFAULT '0',
  `reserveTargetMatItemUUID` varchar(100) DEFAULT NULL,
  `reserveTargetDocMatItemArrayUUID` text,
  `reservedMatItemUUID` varchar(100) DEFAULT NULL,
  `reservedDocType` int DEFAULT '0',
  `reservedDocMatItemArrayUUID` text,
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- schema: logistics
CREATE TABLE IF NOT EXISTS `logistics`.`QualityInspectMatItem` (
  `uuid` varchar(100) NOT NULL,
  `client` varchar(100) DEFAULT NULL,
  `id` varchar(100) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `parentNodeUUID` varchar(100) DEFAULT NULL,
  `rootNodeUUID` varchar(100) DEFAULT NULL,
  `nodeLevel` int DEFAULT '0',
  `serviceEntityName` varchar(100) DEFAULT NULL,
  `nodeName` varchar(100) DEFAULT NULL,
  `createdBy` varchar(100) DEFAULT NULL,
  `createdTime` datetime DEFAULT NULL,
  `lastUpdateBy` varchar(100) DEFAULT NULL,
  `lastUpdateTime` datetime DEFAULT NULL,
  `nodeSpecifyType` int DEFAULT '0',
  `note` varchar(2000) DEFAULT NULL,
  `resEmployeeUUID` varchar(100) DEFAULT NULL,
  `resOrgUUID` varchar(100) DEFAULT NULL,
  `refUUID` varchar(100) DEFAULT NULL,
  `refSEName` varchar(100) DEFAULT NULL,
  `refNodeName` varchar(100) DEFAULT NULL,
  `refPackageName` varchar(100) DEFAULT NULL,
  `itemStatus` int DEFAULT '0',
  `refUnitUUID` varchar(100) DEFAULT NULL,
  `refMaterialSKUUUID` varchar(100) DEFAULT NULL,
  `amount` double DEFAULT '0',
  `itemPrice` double DEFAULT '0',
  `unitPrice` double DEFAULT '0',
  `currencyCode` varchar(100) DEFAULT NULL,
  `prevDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevDocType` int DEFAULT '0',
  `nextDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextDocType` int DEFAULT '0',
  `refFinMatItemUUID` varchar(100) DEFAULT NULL,
  `productionBatchNumber` varchar(100) DEFAULT NULL,
  `purchaseBatchNumber` varchar(100) DEFAULT NULL,
  `homeDocumentType` int DEFAULT '28',
  `materialStatus` int DEFAULT '1',
  `nextDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `prevDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `itemPriceDisplay` double DEFAULT '0',
  `unitPriceDisplay` double DEFAULT '0',
  `prevProfDocType` int DEFAULT '0',
  `prevProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevProfDocMatItemArrayUUID` text,
  `nextProfDocType` int DEFAULT '0',
  `nextProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextProfDocMatItemArrayUUID` text,
  `reserveTargetDocType` int DEFAULT '0',
  `reserveTargetMatItemUUID` varchar(100) DEFAULT NULL,
  `reserveTargetDocMatItemArrayUUID` text,
  `reservedMatItemUUID` varchar(100) DEFAULT NULL,
  `reservedDocType` int DEFAULT '0',
  `reservedDocMatItemArrayUUID` text,
  `itemInspectType` int DEFAULT '0',
  `itemCheckStatus` int DEFAULT '0',
  `itemCheckResult` int DEFAULT '0',
  `checkDate` date DEFAULT NULL,
  `checkTimes` int DEFAULT '0',
  `sampleRate` double DEFAULT '0',
  `sampleAmount` double DEFAULT '0',
  `sampleUnitUUID` varchar(100) DEFAULT NULL,
  `failAmount` double DEFAULT '0',
  `failRefUnitUUID` varchar(100) DEFAULT NULL,
  `refWarehouseAreaUUID` varchar(100) DEFAULT NULL,
  `refWasteWarehouseUUID` varchar(100) DEFAULT NULL,
  `refWasteWareAreaUUID` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- schema: logistics
CREATE TABLE IF NOT EXISTS `logistics`.`WarehouseStoreItem` (
  `uuid` varchar(100) NOT NULL,
  `client` varchar(100) DEFAULT NULL,
  `id` varchar(100) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `parentNodeUUID` varchar(100) DEFAULT NULL,
  `rootNodeUUID` varchar(100) DEFAULT NULL,
  `nodeLevel` int DEFAULT '0',
  `serviceEntityName` varchar(100) DEFAULT NULL,
  `nodeName` varchar(100) DEFAULT NULL,
  `createdBy` varchar(100) DEFAULT NULL,
  `createdTime` datetime DEFAULT NULL,
  `lastUpdateBy` varchar(100) DEFAULT NULL,
  `lastUpdateTime` datetime DEFAULT NULL,
  `nodeSpecifyType` int DEFAULT '0',
  `note` varchar(2000) DEFAULT NULL,
  `resEmployeeUUID` varchar(100) DEFAULT NULL,
  `resOrgUUID` varchar(100) DEFAULT NULL,
  `refUUID` varchar(100) DEFAULT NULL,
  `refSEName` varchar(100) DEFAULT NULL,
  `refNodeName` varchar(100) DEFAULT NULL,
  `refPackageName` varchar(100) DEFAULT NULL,
  `itemStatus` int DEFAULT '0',
  `refUnitUUID` varchar(100) DEFAULT NULL,
  `refMaterialSKUUUID` varchar(100) DEFAULT NULL,
  `amount` double DEFAULT '0',
  `itemPrice` double DEFAULT '0',
  `unitPrice` double DEFAULT '0',
  `currencyCode` varchar(100) DEFAULT NULL,
  `prevDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevDocType` int DEFAULT '0',
  `nextDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextDocType` int DEFAULT '0',
  `refFinMatItemUUID` varchar(100) DEFAULT NULL,
  `productionBatchNumber` varchar(100) DEFAULT NULL,
  `purchaseBatchNumber` varchar(100) DEFAULT NULL,
  `homeDocumentType` int DEFAULT '30',
  `materialStatus` int DEFAULT '1',
  `nextDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `prevDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `itemPriceDisplay` double DEFAULT '0',
  `unitPriceDisplay` double DEFAULT '0',
  `prevProfDocType` int DEFAULT '0',
  `prevProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevProfDocMatItemArrayUUID` text,
  `nextProfDocType` int DEFAULT '0',
  `nextProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextProfDocMatItemArrayUUID` text,
  `reserveTargetDocType` int DEFAULT '0',
  `reserveTargetMatItemUUID` varchar(100) DEFAULT NULL,
  `reserveTargetDocMatItemArrayUUID` text,
  `reservedMatItemUUID` varchar(100) DEFAULT NULL,
  `reservedDocType` int DEFAULT '0',
  `reservedDocMatItemArrayUUID` text,
  `productionDate` date DEFAULT NULL,
  `refUnitName` varchar(100) DEFAULT NULL,
  `inboundDate` datetime DEFAULT NULL,
  `outboundDate` datetime DEFAULT NULL,
  `refWarehouseUUID` varchar(100) DEFAULT NULL,
  `refWarehouseAreaUUID` varchar(100) DEFAULT NULL,
  `refShelfNumberId` varchar(100) DEFAULT NULL,
  `volume` double DEFAULT '0',
  `weight` double DEFAULT '0',
  `declaredValue` double DEFAULT '0',
  `refMaterialTemplateUUID` varchar(100) DEFAULT NULL,
  `refMaterialSKUId` varchar(100) DEFAULT NULL,
  `refMaterialSKUName` varchar(200) DEFAULT NULL,
  `packageStandard` varchar(200) DEFAULT NULL,
  `productionPlace` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- schema: logistics
CREATE TABLE IF NOT EXISTS `logistics`.`WasteProcessMaterialItem` (
  `uuid` varchar(100) NOT NULL,
  `client` varchar(100) DEFAULT NULL,
  `id` varchar(100) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `parentNodeUUID` varchar(100) DEFAULT NULL,
  `rootNodeUUID` varchar(100) DEFAULT NULL,
  `nodeLevel` int DEFAULT '0',
  `serviceEntityName` varchar(100) DEFAULT NULL,
  `nodeName` varchar(100) DEFAULT NULL,
  `createdBy` varchar(100) DEFAULT NULL,
  `createdTime` datetime DEFAULT NULL,
  `lastUpdateBy` varchar(100) DEFAULT NULL,
  `lastUpdateTime` datetime DEFAULT NULL,
  `nodeSpecifyType` int DEFAULT '0',
  `note` varchar(2000) DEFAULT NULL,
  `resEmployeeUUID` varchar(100) DEFAULT NULL,
  `resOrgUUID` varchar(100) DEFAULT NULL,
  `refUUID` varchar(100) DEFAULT NULL,
  `refSEName` varchar(100) DEFAULT NULL,
  `refNodeName` varchar(100) DEFAULT NULL,
  `refPackageName` varchar(100) DEFAULT NULL,
  `itemStatus` int DEFAULT '0',
  `refUnitUUID` varchar(100) DEFAULT NULL,
  `refMaterialSKUUUID` varchar(100) DEFAULT NULL,
  `amount` double DEFAULT '0',
  `itemPrice` double DEFAULT '0',
  `unitPrice` double DEFAULT '0',
  `currencyCode` varchar(100) DEFAULT NULL,
  `prevDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevDocType` int DEFAULT '0',
  `nextDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextDocType` int DEFAULT '0',
  `refFinMatItemUUID` varchar(100) DEFAULT NULL,
  `productionBatchNumber` varchar(100) DEFAULT NULL,
  `purchaseBatchNumber` varchar(100) DEFAULT NULL,
  `homeDocumentType` int DEFAULT '38',
  `materialStatus` int DEFAULT '1',
  `nextDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `prevDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `itemPriceDisplay` double DEFAULT '0',
  `unitPriceDisplay` double DEFAULT '0',
  `prevProfDocType` int DEFAULT '0',
  `prevProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevProfDocMatItemArrayUUID` text,
  `nextProfDocType` int DEFAULT '0',
  `nextProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextProfDocMatItemArrayUUID` text,
  `reserveTargetDocType` int DEFAULT '0',
  `reserveTargetMatItemUUID` varchar(100) DEFAULT NULL,
  `reserveTargetDocMatItemArrayUUID` text,
  `reservedMatItemUUID` varchar(100) DEFAULT NULL,
  `reservedDocType` int DEFAULT '0',
  `reservedDocMatItemArrayUUID` text,
  `storeCheckStatus` int DEFAULT '0',
  `refStoreItemUUID` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- schema: logistics
CREATE TABLE IF NOT EXISTS `logistics`.`InventoryCheckItem` (
  `uuid` varchar(100) NOT NULL,
  `client` varchar(100) DEFAULT NULL,
  `id` varchar(100) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `parentNodeUUID` varchar(100) DEFAULT NULL,
  `rootNodeUUID` varchar(100) DEFAULT NULL,
  `nodeLevel` int DEFAULT '0',
  `serviceEntityName` varchar(100) DEFAULT NULL,
  `nodeName` varchar(100) DEFAULT NULL,
  `createdBy` varchar(100) DEFAULT NULL,
  `createdTime` datetime DEFAULT NULL,
  `lastUpdateBy` varchar(100) DEFAULT NULL,
  `lastUpdateTime` datetime DEFAULT NULL,
  `nodeSpecifyType` int DEFAULT '0',
  `note` varchar(2000) DEFAULT NULL,
  `resEmployeeUUID` varchar(100) DEFAULT NULL,
  `resOrgUUID` varchar(100) DEFAULT NULL,
  `refUUID` varchar(100) DEFAULT NULL,
  `refSEName` varchar(100) DEFAULT NULL,
  `refNodeName` varchar(100) DEFAULT NULL,
  `refPackageName` varchar(100) DEFAULT NULL,
  `itemStatus` int DEFAULT '0',
  `refUnitUUID` varchar(100) DEFAULT NULL,
  `refMaterialSKUUUID` varchar(100) DEFAULT NULL,
  `amount` double DEFAULT '0',
  `itemPrice` double DEFAULT '0',
  `unitPrice` double DEFAULT '0',
  `currencyCode` varchar(100) DEFAULT NULL,
  `prevDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevDocType` int DEFAULT '0',
  `nextDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextDocType` int DEFAULT '0',
  `refFinMatItemUUID` varchar(100) DEFAULT NULL,
  `productionBatchNumber` varchar(100) DEFAULT NULL,
  `purchaseBatchNumber` varchar(100) DEFAULT NULL,
  `homeDocumentType` int DEFAULT '13',
  `materialStatus` int DEFAULT '1',
  `nextDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `prevDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `itemPriceDisplay` double DEFAULT '0',
  `unitPriceDisplay` double DEFAULT '0',
  `prevProfDocType` int DEFAULT '0',
  `prevProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevProfDocMatItemArrayUUID` text,
  `nextProfDocType` int DEFAULT '0',
  `nextProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextProfDocMatItemArrayUUID` text,
  `reserveTargetDocType` int DEFAULT '0',
  `reserveTargetMatItemUUID` varchar(100) DEFAULT NULL,
  `reserveTargetDocMatItemArrayUUID` text,
  `reservedMatItemUUID` varchar(100) DEFAULT NULL,
  `reservedDocType` int DEFAULT '0',
  `reservedDocMatItemArrayUUID` text,
  `refWarehouseStoreItemUUID` varchar(100) DEFAULT NULL,
  `declaredValue` double DEFAULT '0',
  `resultAmount` double DEFAULT '0',
  `resultUnitUUID` varchar(100) DEFAULT NULL,
  `resultDeclaredValue` double DEFAULT '0',
  `inventCheckResult` int DEFAULT '1',
  `updateAmount` double DEFAULT '0',
  `updateDeclaredValue` double DEFAULT '0',
  `updateUnitUUID` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- schema: logistics
CREATE TABLE IF NOT EXISTS `logistics`.`InboundItem` (
  `uuid` varchar(100) NOT NULL,
  `client` varchar(100) DEFAULT NULL,
  `id` varchar(100) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `parentNodeUUID` varchar(100) DEFAULT NULL,
  `rootNodeUUID` varchar(100) DEFAULT NULL,
  `nodeLevel` int DEFAULT '0',
  `serviceEntityName` varchar(100) DEFAULT NULL,
  `nodeName` varchar(100) DEFAULT NULL,
  `createdBy` varchar(100) DEFAULT NULL,
  `createdTime` datetime DEFAULT NULL,
  `lastUpdateBy` varchar(100) DEFAULT NULL,
  `lastUpdateTime` datetime DEFAULT NULL,
  `nodeSpecifyType` int DEFAULT '0',
  `note` varchar(2000) DEFAULT NULL,
  `resEmployeeUUID` varchar(100) DEFAULT NULL,
  `resOrgUUID` varchar(100) DEFAULT NULL,
  `refUUID` varchar(100) DEFAULT NULL,
  `refSEName` varchar(100) DEFAULT NULL,
  `refNodeName` varchar(100) DEFAULT NULL,
  `refPackageName` varchar(100) DEFAULT NULL,
  `itemStatus` int DEFAULT '0',
  `refUnitUUID` varchar(100) DEFAULT NULL,
  `refMaterialSKUUUID` varchar(100) DEFAULT NULL,
  `amount` double DEFAULT '0',
  `itemPrice` double DEFAULT '0',
  `unitPrice` double DEFAULT '0',
  `currencyCode` varchar(100) DEFAULT NULL,
  `prevDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevDocType` int DEFAULT '0',
  `nextDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextDocType` int DEFAULT '0',
  `refFinMatItemUUID` varchar(100) DEFAULT NULL,
  `productionBatchNumber` varchar(100) DEFAULT NULL,
  `purchaseBatchNumber` varchar(100) DEFAULT NULL,
  `homeDocumentType` int DEFAULT '11',
  `materialStatus` int DEFAULT '1',
  `nextDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `prevDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `itemPriceDisplay` double DEFAULT '0',
  `unitPriceDisplay` double DEFAULT '0',
  `prevProfDocType` int DEFAULT '0',
  `prevProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevProfDocMatItemArrayUUID` text,
  `nextProfDocType` int DEFAULT '0',
  `nextProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextProfDocMatItemArrayUUID` text,
  `reserveTargetDocType` int DEFAULT '0',
  `reserveTargetMatItemUUID` varchar(100) DEFAULT NULL,
  `reserveTargetDocMatItemArrayUUID` text,
  `reservedMatItemUUID` varchar(100) DEFAULT NULL,
  `reservedDocType` int DEFAULT '0',
  `reservedDocMatItemArrayUUID` text,
  `inboundFee` double DEFAULT '0',
  `refStoreItemUUID` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- schema: logistics
CREATE TABLE IF NOT EXISTS `logistics`.`OutboundItem` (
  `uuid` varchar(100) NOT NULL,
  `client` varchar(100) DEFAULT NULL,
  `id` varchar(100) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `parentNodeUUID` varchar(100) DEFAULT NULL,
  `rootNodeUUID` varchar(100) DEFAULT NULL,
  `nodeLevel` int DEFAULT '0',
  `serviceEntityName` varchar(100) DEFAULT NULL,
  `nodeName` varchar(100) DEFAULT NULL,
  `createdBy` varchar(100) DEFAULT NULL,
  `createdTime` datetime DEFAULT NULL,
  `lastUpdateBy` varchar(100) DEFAULT NULL,
  `lastUpdateTime` datetime DEFAULT NULL,
  `nodeSpecifyType` int DEFAULT '0',
  `note` varchar(2000) DEFAULT NULL,
  `resEmployeeUUID` varchar(100) DEFAULT NULL,
  `resOrgUUID` varchar(100) DEFAULT NULL,
  `refUUID` varchar(100) DEFAULT NULL,
  `refSEName` varchar(100) DEFAULT NULL,
  `refNodeName` varchar(100) DEFAULT NULL,
  `refPackageName` varchar(100) DEFAULT NULL,
  `itemStatus` int DEFAULT '0',
  `refUnitUUID` varchar(100) DEFAULT NULL,
  `refMaterialSKUUUID` varchar(100) DEFAULT NULL,
  `amount` double DEFAULT '0',
  `itemPrice` double DEFAULT '0',
  `unitPrice` double DEFAULT '0',
  `currencyCode` varchar(100) DEFAULT NULL,
  `prevDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevDocType` int DEFAULT '0',
  `nextDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextDocType` int DEFAULT '0',
  `refFinMatItemUUID` varchar(100) DEFAULT NULL,
  `productionBatchNumber` varchar(100) DEFAULT NULL,
  `purchaseBatchNumber` varchar(100) DEFAULT NULL,
  `homeDocumentType` int DEFAULT '12',
  `materialStatus` int DEFAULT '1',
  `nextDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `prevDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `itemPriceDisplay` double DEFAULT '0',
  `unitPriceDisplay` double DEFAULT '0',
  `prevProfDocType` int DEFAULT '0',
  `prevProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevProfDocMatItemArrayUUID` text,
  `nextProfDocType` int DEFAULT '0',
  `nextProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextProfDocMatItemArrayUUID` text,
  `reserveTargetDocType` int DEFAULT '0',
  `reserveTargetMatItemUUID` varchar(100) DEFAULT NULL,
  `reserveTargetDocMatItemArrayUUID` text,
  `reservedMatItemUUID` varchar(100) DEFAULT NULL,
  `reservedDocType` int DEFAULT '0',
  `reservedDocMatItemArrayUUID` text,
  `outboundFee` double DEFAULT '0',
  `storageFee` double DEFAULT '0',
  `refStoreItemUUID` varchar(100) DEFAULT NULL,
  `storeDay` int DEFAULT '0',
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- schema: sales
CREATE TABLE IF NOT EXISTS `sales`.`SalesForcastMaterialItem` (
  `uuid` varchar(100) NOT NULL,
  `client` varchar(100) DEFAULT NULL,
  `id` varchar(100) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `parentNodeUUID` varchar(100) DEFAULT NULL,
  `rootNodeUUID` varchar(100) DEFAULT NULL,
  `nodeLevel` int DEFAULT '0',
  `serviceEntityName` varchar(100) DEFAULT NULL,
  `nodeName` varchar(100) DEFAULT NULL,
  `createdBy` varchar(100) DEFAULT NULL,
  `createdTime` datetime DEFAULT NULL,
  `lastUpdateBy` varchar(100) DEFAULT NULL,
  `lastUpdateTime` datetime DEFAULT NULL,
  `nodeSpecifyType` int DEFAULT '0',
  `note` varchar(2000) DEFAULT NULL,
  `resEmployeeUUID` varchar(100) DEFAULT NULL,
  `resOrgUUID` varchar(100) DEFAULT NULL,
  `refUUID` varchar(100) DEFAULT NULL,
  `refSEName` varchar(100) DEFAULT NULL,
  `refNodeName` varchar(100) DEFAULT NULL,
  `refPackageName` varchar(100) DEFAULT NULL,
  `itemStatus` int DEFAULT '0',
  `refUnitUUID` varchar(100) DEFAULT NULL,
  `refMaterialSKUUUID` varchar(100) DEFAULT NULL,
  `amount` double DEFAULT '0',
  `itemPrice` double DEFAULT '0',
  `unitPrice` double DEFAULT '0',
  `currencyCode` varchar(100) DEFAULT NULL,
  `prevDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevDocType` int DEFAULT '0',
  `nextDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextDocType` int DEFAULT '0',
  `refFinMatItemUUID` varchar(100) DEFAULT NULL,
  `productionBatchNumber` varchar(100) DEFAULT NULL,
  `purchaseBatchNumber` varchar(100) DEFAULT NULL,
  `homeDocumentType` int DEFAULT '33',
  `materialStatus` int DEFAULT '1',
  `nextDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `prevDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `itemPriceDisplay` double DEFAULT '0',
  `unitPriceDisplay` double DEFAULT '0',
  `prevProfDocType` int DEFAULT '0',
  `prevProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevProfDocMatItemArrayUUID` text,
  `nextProfDocType` int DEFAULT '0',
  `nextProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextProfDocMatItemArrayUUID` text,
  `reserveTargetDocType` int DEFAULT '0',
  `reserveTargetMatItemUUID` varchar(100) DEFAULT NULL,
  `reserveTargetDocMatItemArrayUUID` text,
  `reservedMatItemUUID` varchar(100) DEFAULT NULL,
  `reservedDocType` int DEFAULT '0',
  `reservedDocMatItemArrayUUID` text,
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- schema: sales
CREATE TABLE IF NOT EXISTS `sales`.`SalesReturnMaterialItem` (
  `uuid` varchar(100) NOT NULL,
  `client` varchar(100) DEFAULT NULL,
  `id` varchar(100) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `parentNodeUUID` varchar(100) DEFAULT NULL,
  `rootNodeUUID` varchar(100) DEFAULT NULL,
  `nodeLevel` int DEFAULT '0',
  `serviceEntityName` varchar(100) DEFAULT NULL,
  `nodeName` varchar(100) DEFAULT NULL,
  `createdBy` varchar(100) DEFAULT NULL,
  `createdTime` datetime DEFAULT NULL,
  `lastUpdateBy` varchar(100) DEFAULT NULL,
  `lastUpdateTime` datetime DEFAULT NULL,
  `nodeSpecifyType` int DEFAULT '0',
  `note` varchar(2000) DEFAULT NULL,
  `resEmployeeUUID` varchar(100) DEFAULT NULL,
  `resOrgUUID` varchar(100) DEFAULT NULL,
  `refUUID` varchar(100) DEFAULT NULL,
  `refSEName` varchar(100) DEFAULT NULL,
  `refNodeName` varchar(100) DEFAULT NULL,
  `refPackageName` varchar(100) DEFAULT NULL,
  `itemStatus` int DEFAULT '0',
  `refUnitUUID` varchar(100) DEFAULT NULL,
  `refMaterialSKUUUID` varchar(100) DEFAULT NULL,
  `amount` double DEFAULT '0',
  `itemPrice` double DEFAULT '0',
  `unitPrice` double DEFAULT '0',
  `currencyCode` varchar(100) DEFAULT NULL,
  `prevDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevDocType` int DEFAULT '0',
  `nextDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextDocType` int DEFAULT '0',
  `refFinMatItemUUID` varchar(100) DEFAULT NULL,
  `productionBatchNumber` varchar(100) DEFAULT NULL,
  `purchaseBatchNumber` varchar(100) DEFAULT NULL,
  `homeDocumentType` int DEFAULT '18',
  `materialStatus` int DEFAULT '1',
  `nextDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `prevDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `itemPriceDisplay` double DEFAULT '0',
  `unitPriceDisplay` double DEFAULT '0',
  `prevProfDocType` int DEFAULT '0',
  `prevProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevProfDocMatItemArrayUUID` text,
  `nextProfDocType` int DEFAULT '0',
  `nextProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextProfDocMatItemArrayUUID` text,
  `reserveTargetDocType` int DEFAULT '0',
  `reserveTargetMatItemUUID` varchar(100) DEFAULT NULL,
  `reserveTargetDocMatItemArrayUUID` text,
  `reservedMatItemUUID` varchar(100) DEFAULT NULL,
  `reservedDocType` int DEFAULT '0',
  `reservedDocMatItemArrayUUID` text,
  `refFinAccountUUID` varchar(100) DEFAULT NULL,
  `refDocItemUUID` varchar(100) DEFAULT NULL,
  `refDocItemType` int DEFAULT '0',
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- schema: sales
CREATE TABLE IF NOT EXISTS `sales`.`SalesContractMaterialItem` (
  `uuid` varchar(100) NOT NULL,
  `client` varchar(100) DEFAULT NULL,
  `id` varchar(100) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `parentNodeUUID` varchar(100) DEFAULT NULL,
  `rootNodeUUID` varchar(100) DEFAULT NULL,
  `nodeLevel` int DEFAULT '0',
  `serviceEntityName` varchar(100) DEFAULT NULL,
  `nodeName` varchar(100) DEFAULT NULL,
  `createdBy` varchar(100) DEFAULT NULL,
  `createdTime` datetime DEFAULT NULL,
  `lastUpdateBy` varchar(100) DEFAULT NULL,
  `lastUpdateTime` datetime DEFAULT NULL,
  `nodeSpecifyType` int DEFAULT '0',
  `note` varchar(2000) DEFAULT NULL,
  `resEmployeeUUID` varchar(100) DEFAULT NULL,
  `resOrgUUID` varchar(100) DEFAULT NULL,
  `refUUID` varchar(100) DEFAULT NULL,
  `refSEName` varchar(100) DEFAULT NULL,
  `refNodeName` varchar(100) DEFAULT NULL,
  `refPackageName` varchar(100) DEFAULT NULL,
  `itemStatus` int DEFAULT '0',
  `refUnitUUID` varchar(100) DEFAULT NULL,
  `refMaterialSKUUUID` varchar(100) DEFAULT NULL,
  `amount` double DEFAULT '0',
  `itemPrice` double DEFAULT '0',
  `unitPrice` double DEFAULT '0',
  `currencyCode` varchar(100) DEFAULT NULL,
  `prevDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevDocType` int DEFAULT '0',
  `nextDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextDocType` int DEFAULT '0',
  `refFinMatItemUUID` varchar(100) DEFAULT NULL,
  `productionBatchNumber` varchar(100) DEFAULT NULL,
  `purchaseBatchNumber` varchar(100) DEFAULT NULL,
  `homeDocumentType` int DEFAULT '19',
  `materialStatus` int DEFAULT '1',
  `nextDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `prevDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `itemPriceDisplay` double DEFAULT '0',
  `unitPriceDisplay` double DEFAULT '0',
  `prevProfDocType` int DEFAULT '0',
  `prevProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevProfDocMatItemArrayUUID` text,
  `nextProfDocType` int DEFAULT '0',
  `nextProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextProfDocMatItemArrayUUID` text,
  `reserveTargetDocType` int DEFAULT '0',
  `reserveTargetMatItemUUID` varchar(100) DEFAULT NULL,
  `reserveTargetDocMatItemArrayUUID` text,
  `reservedMatItemUUID` varchar(100) DEFAULT NULL,
  `reservedDocType` int DEFAULT '0',
  `reservedDocMatItemArrayUUID` text,
  `shippingPoint` varchar(100) DEFAULT NULL,
  `requireShippingTime` datetime DEFAULT NULL,
  `requirementNote` varchar(500) DEFAULT NULL,
  `refTechStandard` varchar(200) DEFAULT NULL,
  `refUnitName` varchar(100) DEFAULT NULL,
  `refStoreItemUUID` varchar(100) DEFAULT NULL,
  `refFinAccountUUID` varchar(100) DEFAULT NULL,
  `refOutboundItemUUID` varchar(100) DEFAULT NULL,
  `deliveryDoneBy` varchar(100) DEFAULT NULL,
  `deliveryDoneTime` datetime DEFAULT NULL,
  `processDoneBy` varchar(100) DEFAULT NULL,
  `processDoneTime` datetime DEFAULT NULL,
  `storeCheckStatus` int DEFAULT '0',
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- schema: production
CREATE TABLE IF NOT EXISTS `production`.`ProductionOrderItem` (
  `uuid` varchar(100) NOT NULL,
  `client` varchar(100) DEFAULT NULL,
  `id` varchar(100) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `parentNodeUUID` varchar(100) DEFAULT NULL,
  `rootNodeUUID` varchar(100) DEFAULT NULL,
  `nodeLevel` int DEFAULT '0',
  `serviceEntityName` varchar(100) DEFAULT NULL,
  `nodeName` varchar(100) DEFAULT NULL,
  `createdBy` varchar(100) DEFAULT NULL,
  `createdTime` datetime DEFAULT NULL,
  `lastUpdateBy` varchar(100) DEFAULT NULL,
  `lastUpdateTime` datetime DEFAULT NULL,
  `nodeSpecifyType` int DEFAULT '0',
  `note` varchar(2000) DEFAULT NULL,
  `resEmployeeUUID` varchar(100) DEFAULT NULL,
  `resOrgUUID` varchar(100) DEFAULT NULL,
  `refUUID` varchar(100) DEFAULT NULL,
  `refSEName` varchar(100) DEFAULT NULL,
  `refNodeName` varchar(100) DEFAULT NULL,
  `refPackageName` varchar(100) DEFAULT NULL,
  `itemStatus` int DEFAULT '0',
  `refUnitUUID` varchar(100) DEFAULT NULL,
  `refMaterialSKUUUID` varchar(100) DEFAULT NULL,
  `amount` double DEFAULT '0',
  `itemPrice` double DEFAULT '0',
  `unitPrice` double DEFAULT '0',
  `currencyCode` varchar(100) DEFAULT NULL,
  `prevDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevDocType` int DEFAULT '0',
  `nextDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextDocType` int DEFAULT '0',
  `refFinMatItemUUID` varchar(100) DEFAULT NULL,
  `productionBatchNumber` varchar(100) DEFAULT NULL,
  `purchaseBatchNumber` varchar(100) DEFAULT NULL,
  `homeDocumentType` int DEFAULT '31',
  `materialStatus` int DEFAULT '1',
  `nextDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `prevDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `itemPriceDisplay` double DEFAULT '0',
  `unitPriceDisplay` double DEFAULT '0',
  `prevProfDocType` int DEFAULT '0',
  `prevProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevProfDocMatItemArrayUUID` text,
  `nextProfDocType` int DEFAULT '0',
  `nextProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextProfDocMatItemArrayUUID` text,
  `reserveTargetDocType` int DEFAULT '0',
  `reserveTargetMatItemUUID` varchar(100) DEFAULT NULL,
  `reserveTargetDocMatItemArrayUUID` text,
  `reservedMatItemUUID` varchar(100) DEFAULT NULL,
  `reservedDocType` int DEFAULT '0',
  `reservedDocMatItemArrayUUID` text,
  `itemCategory` int DEFAULT '0',
  `planAmount` double DEFAULT '0',
  `actualAmount` double DEFAULT '0',
  `scrapAmount` double DEFAULT '0',
  `pickAmount` double DEFAULT '0',
  `supplyAmount` double DEFAULT '0',
  `unitCost` double DEFAULT '0',
  `grossCost` double DEFAULT '0',
  `itemCostLossRate` double DEFAULT '0',
  `itemCostActual` double DEFAULT '0',
  `amountWithLossRate` double DEFAULT '0',
  `availableAmount` double DEFAULT '0',
  `inStockAmount` double DEFAULT '0',
  `toPickAmount` double DEFAULT '0',
  `inProcessAmount` double DEFAULT '0',
  `selfLeadTime` double DEFAULT '0',
  `comLeadTime` double DEFAULT '0',
  `planStartDate` date DEFAULT NULL,
  `planStartPrepareDate` date DEFAULT NULL,
  `planEndDate` date DEFAULT NULL,
  `refBOMItemUUID` varchar(100) DEFAULT NULL,
  `refRouteProcessItemUUID` varchar(100) DEFAULT NULL,
  `refWarehouseUUID` varchar(100) DEFAULT NULL,
  `refWarehouseAreaUUID` varchar(100) DEFAULT NULL,
  `productionDate` date DEFAULT NULL,
  `requireDate` date DEFAULT NULL,
  `suppliedAmount` double DEFAULT '0',
  `lackInPlanAmount` double DEFAULT '0',
  `pickedAmount` double DEFAULT '0',
  `pickStatus` int DEFAULT '0',
  `actualStartDate` date DEFAULT NULL,
  `actualEndDate` date DEFAULT NULL,
  `actualStartPrepareDate` date DEFAULT NULL,
  `itemCostNoTax` double DEFAULT '0',
  `unitCostNoTax` double DEFAULT '0',
  `taxRate` double DEFAULT '0',
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- schema: production
CREATE TABLE IF NOT EXISTS `production`.`ProdOrderTargetMatItem` (
  `uuid` varchar(100) NOT NULL,
  `client` varchar(100) DEFAULT NULL,
  `id` varchar(100) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `parentNodeUUID` varchar(100) DEFAULT NULL,
  `rootNodeUUID` varchar(100) DEFAULT NULL,
  `nodeLevel` int DEFAULT '0',
  `serviceEntityName` varchar(100) DEFAULT NULL,
  `nodeName` varchar(100) DEFAULT NULL,
  `createdBy` varchar(100) DEFAULT NULL,
  `createdTime` datetime DEFAULT NULL,
  `lastUpdateBy` varchar(100) DEFAULT NULL,
  `lastUpdateTime` datetime DEFAULT NULL,
  `nodeSpecifyType` int DEFAULT '0',
  `note` varchar(2000) DEFAULT NULL,
  `resEmployeeUUID` varchar(100) DEFAULT NULL,
  `resOrgUUID` varchar(100) DEFAULT NULL,
  `refUUID` varchar(100) DEFAULT NULL,
  `refSEName` varchar(100) DEFAULT NULL,
  `refNodeName` varchar(100) DEFAULT NULL,
  `refPackageName` varchar(100) DEFAULT NULL,
  `itemStatus` int DEFAULT '0',
  `refUnitUUID` varchar(100) DEFAULT NULL,
  `refMaterialSKUUUID` varchar(100) DEFAULT NULL,
  `amount` double DEFAULT '0',
  `itemPrice` double DEFAULT '0',
  `unitPrice` double DEFAULT '0',
  `currencyCode` varchar(100) DEFAULT NULL,
  `prevDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevDocType` int DEFAULT '0',
  `nextDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextDocType` int DEFAULT '0',
  `refFinMatItemUUID` varchar(100) DEFAULT NULL,
  `productionBatchNumber` varchar(100) DEFAULT NULL,
  `purchaseBatchNumber` varchar(100) DEFAULT NULL,
  `homeDocumentType` int DEFAULT '17',
  `materialStatus` int DEFAULT '1',
  `nextDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `prevDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `itemPriceDisplay` double DEFAULT '0',
  `unitPriceDisplay` double DEFAULT '0',
  `prevProfDocType` int DEFAULT '0',
  `prevProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevProfDocMatItemArrayUUID` text,
  `nextProfDocType` int DEFAULT '0',
  `nextProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextProfDocMatItemArrayUUID` text,
  `reserveTargetDocType` int DEFAULT '0',
  `reserveTargetMatItemUUID` varchar(100) DEFAULT NULL,
  `reserveTargetDocMatItemArrayUUID` text,
  `reservedMatItemUUID` varchar(100) DEFAULT NULL,
  `reservedDocType` int DEFAULT '0',
  `reservedDocMatItemArrayUUID` text,
  `processIndex` int DEFAULT '0',
  `refSerialId` varchar(100) DEFAULT NULL,
  `planAmount` double DEFAULT '0',
  `actualAmount` double DEFAULT '0',
  `scrapAmount` double DEFAULT '0',
  `unitCost` double DEFAULT '0',
  `grossCost` double DEFAULT '0',
  `refWarehouseUUID` varchar(100) DEFAULT NULL,
  `refWarehouseAreaUUID` varchar(100) DEFAULT NULL,
  `productionDate` date DEFAULT NULL,
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- schema: finance
CREATE TABLE IF NOT EXISTS `finance`.`FinAccountMaterialItem` (
  `uuid` varchar(100) NOT NULL,
  `client` varchar(100) DEFAULT NULL,
  `id` varchar(100) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `parentNodeUUID` varchar(100) DEFAULT NULL,
  `rootNodeUUID` varchar(100) DEFAULT NULL,
  `nodeLevel` int DEFAULT '0',
  `serviceEntityName` varchar(100) DEFAULT NULL,
  `nodeName` varchar(100) DEFAULT NULL,
  `createdBy` varchar(100) DEFAULT NULL,
  `createdTime` datetime DEFAULT NULL,
  `lastUpdateBy` varchar(100) DEFAULT NULL,
  `lastUpdateTime` datetime DEFAULT NULL,
  `nodeSpecifyType` int DEFAULT '0',
  `note` varchar(2000) DEFAULT NULL,
  `resEmployeeUUID` varchar(100) DEFAULT NULL,
  `resOrgUUID` varchar(100) DEFAULT NULL,
  `refUUID` varchar(100) DEFAULT NULL,
  `refSEName` varchar(100) DEFAULT NULL,
  `refNodeName` varchar(100) DEFAULT NULL,
  `refPackageName` varchar(100) DEFAULT NULL,
  `itemStatus` int DEFAULT '0',
  `refUnitUUID` varchar(100) DEFAULT NULL,
  `refMaterialSKUUUID` varchar(100) DEFAULT NULL,
  `amount` double DEFAULT '0',
  `itemPrice` double DEFAULT '0',
  `unitPrice` double DEFAULT '0',
  `currencyCode` varchar(100) DEFAULT NULL,
  `prevDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevDocType` int DEFAULT '0',
  `nextDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextDocType` int DEFAULT '0',
  `refFinMatItemUUID` varchar(100) DEFAULT NULL,
  `productionBatchNumber` varchar(100) DEFAULT NULL,
  `purchaseBatchNumber` varchar(100) DEFAULT NULL,
  `homeDocumentType` int DEFAULT '4',
  `materialStatus` int DEFAULT '1',
  `nextDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `prevDocMatItemArrayUUID` varchar(2000) DEFAULT NULL,
  `itemPriceDisplay` double DEFAULT '0',
  `unitPriceDisplay` double DEFAULT '0',
  `prevProfDocType` int DEFAULT '0',
  `prevProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `prevProfDocMatItemArrayUUID` text,
  `nextProfDocType` int DEFAULT '0',
  `nextProfDocMatItemUUID` varchar(100) DEFAULT NULL,
  `nextProfDocMatItemArrayUUID` text,
  `reserveTargetDocType` int DEFAULT '0',
  `reserveTargetMatItemUUID` varchar(100) DEFAULT NULL,
  `reserveTargetDocMatItemArrayUUID` text,
  `reservedMatItemUUID` varchar(100) DEFAULT NULL,
  `reservedDocType` int DEFAULT '0',
  `reservedDocMatItemArrayUUID` text,
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
